<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hide</name>
   <tag></tag>
   <elementGuidId>e3e45db9-65a1-4bdb-8d30-ffc3acd31bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_new_show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='password_new_show']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edaefd28-3c6c-41ac-8900-f70c6a599a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9okv _4jy3 _517h _51sy</value>
      <webElementGuid>76a74f85-339b-43de-b7be-2d5839d5903d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_new_show</value>
      <webElementGuid>8b7705e7-4a38-4a31-9560-06d0177ff17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>533a2ec4-d1b8-4ba3-ad30-034196976062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>48353028-658f-4cc8-af0c-8b37a702c667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_new_show&quot;)</value>
      <webElementGuid>f15cd5cb-cd5c-4405-8392-745f322d6749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='password_new_show']</value>
      <webElementGuid>ceb624fc-d8dd-4b05-8ec1-861ff81999ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_a_kM']/div/div[2]/div[2]/div/div/button</value>
      <webElementGuid>780f15b4-db2a-40e2-881c-5d6a1223fa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a new password'])[1]/following::button[1]</value>
      <webElementGuid>a9082efa-cf50-4765-bff4-757476bcc7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::button[1]</value>
      <webElementGuid>1e1876e4-72cf-4677-b84c-b6dce9db3797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/preceding::button[1]</value>
      <webElementGuid>c485aa9f-a8a9-4c60-8b78-a235dfa17043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check the help tag for password feedback'])[1]/preceding::button[2]</value>
      <webElementGuid>62377856-702e-410f-81ab-729f56c6352e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hide']/parent::*</value>
      <webElementGuid>2c4b9400-8547-4c1e-b2f4-d21dc1577300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9deba721-8396-4e2c-9651-bd74505ac6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'password_new_show' and @type = 'button' and (text() = 'Hide' or . = 'Hide')]</value>
      <webElementGuid>387432e0-509f-48e2-a9d0-ba54c93f702d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
