<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a new password_password_new</name>
   <tag></tag>
   <elementGuidId>5bd20e41-578a-4f26-964e-5a70bc3b06e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8290df80-a787-47f4-9ab5-47eae7c8f661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>624e4b05-0c8f-44e0-89fa-b9dfd80383e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _55r1 _9oku _9o1w</value>
      <webElementGuid>9fdeec73-fc37-488a-bbd4-a51d3558dacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_new</value>
      <webElementGuid>0540fad5-a4c2-4324-9464-846ef25f4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_new</value>
      <webElementGuid>f366493d-41ae-42e1-95b2-c110bc0ffb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>54d431dd-52b6-4df0-a95d-cc573afeab63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d22db612-d30d-4ae1-bd30-59c76ef0619f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>57f0dd24-7c57-4609-9276-242ed50b4c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>password_new_status</value>
      <webElementGuid>3458e734-fc99-4481-8f16-3f40d6774537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_new&quot;)</value>
      <webElementGuid>e41871ea-84c0-4b64-8df7-e9161ab6d0d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_new']</value>
      <webElementGuid>2f637833-4d50-42c4-a624-f7b0c0230e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_a_kM']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>7d5f4b16-9afe-4570-8a98-2ce008f2240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>463c916e-703f-4acf-aaf7-ad812e8f3a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'password_new' and @name = 'password_new' and @placeholder = 'New password']</value>
      <webElementGuid>4b042e47-9dd3-4359-8b94-b21516ca3886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
