<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a new password_password_new_1</name>
   <tag></tag>
   <elementGuidId>d2815a5e-6769-48e7-99c2-515c46de1b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42ad399c-fdf1-4a00-805b-20196814e403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>da946671-c7d9-4b80-91fa-6a1aa61ad445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _55r1 _9oku _9o1w</value>
      <webElementGuid>b8df1a9a-16b6-424d-a7e9-cfb2b6023283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_new</value>
      <webElementGuid>1b0bde55-69fb-4d3f-ad40-a3f7202fd62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_new</value>
      <webElementGuid>d4180bb7-7104-4da5-b9d1-30b26bc71d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>5d9f2628-5997-4474-8e14-2ddc479d4765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>429938d1-5b9d-46d2-85b4-9ff2d0885c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>43ceb12d-c1df-4945-8f84-3e873e7d1639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>password_new_status</value>
      <webElementGuid>dcd7e779-5312-4257-a5c1-cd48588e16ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_new&quot;)</value>
      <webElementGuid>a2ddf629-e276-4793-907e-74c3e55e9ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_new']</value>
      <webElementGuid>0736dd0d-2a9f-4b88-87df-89234063d7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_a_kM']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>7ef329b6-d6c5-4d1b-8f44-aff71618c7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2a1fe0da-0fa3-42f6-b526-2881175ad185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'password_new' and @name = 'password_new' and @placeholder = 'New password']</value>
      <webElementGuid>26fa8422-c58f-4d67-ae17-5553e175d2f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
