<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please check your emails for a messag_6d8c97</name>
   <tag></tag>
   <elementGuidId>39d3d14b-02ef-4a22-bd0f-dd847f686218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recovery_code_entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recovery_code_entry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddfa67f7-05a2-4a73-b8c8-ece34d0fca74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec621e60-e5a8-49f9-bc57-d6ed22937f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _9o1w _9o1_</value>
      <webElementGuid>c283e36e-dce8-497d-816a-2bc3e900610f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>67d10dae-0ddb-4801-8b20-16b61e1120ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recovery_code_entry</value>
      <webElementGuid>ab226095-5110-4fd8-9a63-b84678a47e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>d9157e64-2578-439e-8ccd-3f97e2867b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>18261c0a-f5a1-4eed-9563-fa7800a998c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recovery_code_entry&quot;)</value>
      <webElementGuid>0d945777-713d-4390-8587-7424a73cb562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recovery_code_entry']</value>
      <webElementGuid>c67d5680-e91c-417c-bed0-971501f1e61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_a_Jr']/div/div[2]/div[3]/div/input</value>
      <webElementGuid>e10ac9c6-6d71-4dd4-b388-4431fa6ba70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f92f4ca8-3b71-424f-b5ed-27a63d848e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'n' and @id = 'recovery_code_entry' and @placeholder = 'Enter code']</value>
      <webElementGuid>1c5ed936-4120-4ce8-a9bd-bcba561e8a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
