<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your email address or mo_025e92</name>
   <tag></tag>
   <elementGuidId>2950daab-ecd4-4a32-b8e6-e66a81fcccaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identify_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identify_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8048e611-3401-4c9f-b5c8-0da00ecb99e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b78b7335-92b3-4ab4-861d-dfb96a9f2fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _9o1w</value>
      <webElementGuid>9691d2d9-e891-41d9-8d92-c417d5b2bdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identify_email</value>
      <webElementGuid>15d3bfa8-a708-4c9f-86bd-b8e5e41c14ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>09fd392a-71be-42b3-b932-cf9d4abeb0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address or mobile number</value>
      <webElementGuid>83b1f930-29ff-4feb-a37b-cb74bb1a7316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c32c5205-6c72-4f13-bea2-c64ae1346484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email address or mobile number</value>
      <webElementGuid>a3098c14-4269-4176-8a3d-08e5795dc5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identify_email&quot;)</value>
      <webElementGuid>a65db161-2bbe-42e9-ba64-eb4419bd0257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identify_email']</value>
      <webElementGuid>7680b368-613c-47c0-ac1c-18f0c3f89bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identify_yourself_flow']/div/div[2]/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>95cc0e07-fec7-4256-bc37-28064e498c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>86bd78d6-2396-47f5-9392-25150ef65f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'identify_email' and @name = 'email' and @placeholder = 'Email address or mobile number']</value>
      <webElementGuid>4fa44937-b8fd-416c-a29e-ee806c5dec39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
