<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook helps you connect and share wi_33762e</name>
   <tag></tag>
   <elementGuidId>37d5f1a4-3efd-4763-848c-b874f5c70e57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d27bc33b-d022-476d-8d45-d8ef881824e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6luy _55r1 _1kbt</value>
      <webElementGuid>5f28587d-8eeb-4446-a5fc-c47ffc238774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passContainer</value>
      <webElementGuid>ad9beda1-4b6c-4608-a2ab-a8138b7bc04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passContainer&quot;)</value>
      <webElementGuid>7d499af3-2c1b-464c-a211-63d5b0d93c31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='passContainer']</value>
      <webElementGuid>91093f1a-b44f-4541-bfce-13d51544ba95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_a_Gt']/div/div[2]/div</value>
      <webElementGuid>159e700a-31aa-4ffc-85dd-ec3d519fdd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook helps you connect and share with the people in your life.'])[1]/following::div[7]</value>
      <webElementGuid>df7bc34f-62d5-448f-aafc-ca086fb3f96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::div[14]</value>
      <webElementGuid>f683e021-ed2e-4cd3-bd0b-d35db1ebb7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::div[4]</value>
      <webElementGuid>625624e6-0909-4155-b1f1-6e85196b0fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::div[5]</value>
      <webElementGuid>b99460fc-ef11-4856-953d-67f659b5f223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div</value>
      <webElementGuid>ec849c4b-21ff-4b6d-9c5a-bd78ff5adb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'passContainer']</value>
      <webElementGuid>02e0ba36-7a78-40d7-9f20-526487ed55dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
